services:
  - type: web
    name: baby-bianca-00          # ← new name
    env: python
    buildCommand: "pip install -r requirements.txt"
    # startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    startCommand: "uvicorn baby_bianca_00.app.main:app --host 0.0.0.0 --port $PORT"

    autoDeploy: true
    plan: dtarter
    disk:
      name: data
      mountPath: /opt/render/project/src/app
      sizeGB: 1